services:
  activemq-artemis:
    image: apache/activemq-artemis:latest
    container_name: activemq-artemis
    ports:
      - "61616:61616"  # Core messaging port
      - "8161:8161"    # Web console
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
    volumes:
      - ./artemis-data:/var/lib/artemis-instance
